### ISSUE TITLE
Doesn't work inside <webview>

### ISSUE THREAD

**Issue by nfriend** [parro-it/debug-menu#6]
The context menu opens correctly when a right-clicked occurs inside a `webview`, but the inspector opens up to show the parent context, not the `webview`'s context:

![image](https://cloud.githubusercontent.com/assets/1638631/18389316/c5e181de-767b-11e6-8a1f-a66b0cd399dc.png)

It would be more useful if the `webview`'s inspector tools were automatically opened.

**Comment by nfriend** [comment]
All that is required to fix this issue is to change this (lines 7-16):

``` javascript
function inpectMenuTemplate(pos) {
  return {
    label: 'Inspect element',
    click: () => {
      electron.remote
        .getCurrentWindow()
        .inspectElement(pos.x, pos.y);
    }
  };
}
```

to this:

``` javascript
function inpectMenuTemplate(pos) {
  return {
    label: 'Inspect element',
    click: () => {      
       webview.inspectElement(pos.x, pos.y);
    }
  };
}
```

Perhaps the target of the `inspectElement` call could be passed as an optional parameter during the `install()` function call?

**Comment by parro-it** [comment]
Actually, if you use it as a [electron-contextmenu-middleware](https://github.com/parro-it/electron-contextmenu-middleware) the [middleware method](https://github.com/parro-it/debug-menu/blob/master/index.js#L45) `ctx` argument has a `elm` property containing the element on which the `click` event occur. 

We can use that to discover if the click happens inside a webview. Do you mind making a PR?

**Comment by nfriend** [comment]
Sure, I can give it a shot.  Thanks for the response!

**Comment by teameh** [comment]
I made a PR, hope you don't mind :)
